# .goreleaser.yml
# Build customization
builds:
  - main: app.go
    binary: gomotics
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386
# Archive customization
archive:
  format: tar.gz
  