# .goreleaser.yml
# Build customization
builds:
  - main: app.go
    binary: gomotics
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
# Archive customization
archive:
  format: tar.gz
  files:
    - gomotics.licence.txt
release:
  github:
    owner: mch1307
    name: gomotics    