# .travis.yml
language: go
go:
    - 1.8.3
install: true
sudo: required
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - rm -rf ./dist
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -p 1
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash  
