
[server]
ListenPort = 8081
LogLevel = "INFO"
LogPath = "c:\\temp\\"

[jeedom]
service =   "jeedom.csnet.me"
host =      "jeedom.csnet.me"
port =      80
apiPath =   "/core/api/jeeApi.php?"
apiKey =    ""

[nhc]
host =          "nhc.csnet.me"
port =          8000
registerCmd =   "startevents"
getEquipCmd =   "listactions"
getLocCmd =     "listlocations"
getThermostat = "listthermostat"
getEnergy =     "listenergy"