[server]
listenPort = 8081
logLevel = "DEBUG"
logPath = "."
gmHostPort = "localhost:8081"


[nhc]
host =          "localhost"
port =          8000

[jeedom]
url = "http://jeedom/core/api/jeeApi.php"
apikey = ""
autoCreateObjects = false
