[server]
ListenPort = 8081
LogLevel = "DEBUG"
LogPath = "."
EndpointURL = "localhost"

[nhc]
host =          "localhost"
port =          8000

[jeedom]
url = "http://jeedom/core/api/jeeApi.php"
apikey = ""
AutoCreateNHCObjects = false
